const isadEntryTemplate = {
  legacyId: '',
  parentId: '',
  qubitParentSlug: '',
  identifier: '',
  accessionNumber: '',
  title: '',
  levelOfDescription: '', // Item
  extentAndMedium: '',
  repository: '', // Only link at highest levels
  archivalHistory: '', 
  acquisition: '',
  scopeAndContent: '',
  appraisal: '',
  accruals: '',
  arrangement: '',
  accessConditions: '',
  reproductionConditions: '',
  language: '', // en, es
  script: '',
  languageNote: '',
  physicalCharacteristics: '',
  findingAids: '',
  locationOfOriginals: '',
  locationOfCopies: '',
  relatedUnitsOfDescription: '',
  publicationNote: '',
  digitalObjectPath: '',
  digitalObjectURI: '',
  generalNote: '',
  subjectAccessPoints: '',
  placeAccessPoints: '',
  nameAccessPoints: '',
  genreAccessPoints: '',
  descriptionIdentifier: '',
  institutionIdentifier: '',
  rules: '',
  descriptionStatus: '',
  levelOfDetail: '',
  revisionHistory: '',
  languageOfDescription: '',
  scriptOfDescription: '',
  sources: '',
  archivistNote: '',
  publicationStatus: '',
  physicalObjectName: '',
  physicalObjectLocation: '',
  physicalObjectType: '',
  alternativeIdentifiers: '',
  alternativeIdentifierLabels: '',
  eventDates: '',
  eventTypes: '',
  eventStartDates: '',
  eventEndDates: '',
  eventActors: '',
  eventActorHistories: '',
  culture: '',
};

module.exports = isadEntryTemplate;
